package com.dj.mapper;

import com.dj.model.TbShop;
import com.dj.model.TbShopExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    long countByExample(TbShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    int deleteByExample(TbShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    int insert(TbShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    int insertSelective(TbShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    List<TbShop> selectByExample(TbShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbShop record, @Param("example") TbShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TB_SHOP
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    int updateByExample(@Param("record") TbShop record, @Param("example") TbShopExample example);

    void insert2(List<TbShop> newList);
}