package com.dj.model;

import java.math.BigDecimal;

public class TbShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TB_SHOP.ID
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    private BigDecimal id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TB_SHOP.ID
     *
     * @return the value of SYSTEM.TB_SHOP.ID
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TB_SHOP.ID
     *
     * @param id the value for SYSTEM.TB_SHOP.ID
     *
     * @mbg.generated Sun Sep 08 17:29:23 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }
}